### ISSUE TITLE
!important

### ISSUE THREAD

**Issue by LukyVj** [samthor/rippleJS#2]
Hello, 

Awesome script, it jut seems that your css indications are kinda false? 
I'm forced to make 

``` css
.rippleJS .ripple { background: red !important; }
```

to actually change the color.
